// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzmqgqcrztiamfzjgqvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bXFncWNyenRpYW1mempncXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDgzNDgsImV4cCI6MjA2OTE4NDM0OH0.n09qcUbIjA6WOgKP_dqiRmtNBEgipph-gvXHWx9ZSMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});